# Generated by Django 4.1.7 on 2023-05-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(blank=True, default='8777 777 77 77', max_length=14),
        ),
    ]
