# Generated by Django 4.1.7 on 2023-05-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_woman'),
    ]

    operations = [
        migrations.AddField(
            model_name='woman',
            name='url',
            field=models.SlugField(default='', max_length=160, unique=True),
        ),
    ]
